service:
  name: serverless-todo-app

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs12.x

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

  environment:
    TODOS_TABLE: Todos-${self:provider.stage}
    TODO_ID_INDEX: TodoIdIndex
  
  iamRoleStatments:
    - Effect: Allow
      Action:
        - dynamodb: PutItem
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODOS_TABLE}

functions:

  Auth:
    handler: src/lambda/auth/auth0Authorizer.handler

  # TODO: Configure this function
  GetTodos:
    handler: src/lambda/http/getTodos.handler
    events:
      - http:
          method: get
          path: todos
          cors: true
          
  CreateTodo:
    handler: src/lambda/http/createTodo.handler
    events:
      - http:
          method: post
          path: todos
          cors: true

  # TODO: Configure this function
  UpdateTodo:
    handler: src/lambda/http/updateTodo.handler
    events:
      - http:
          method: patch
          path: todos/{todoId}
          cors: true

  # TODO: Configure this function
  DeleteTodo:
    handler: src/lambda/http/deleteTodo.handler
    events:
      - http:
          method: delete
          path: todos/{todoId}
          cors: true

  # TODO: Configure this function
  GenerateUploadUrl:
    handler: src/lambda/http/generateUploadUrl.handler
    events:
      - http:
          method: post
          path: todos/{todoId}/attachment
          cors: true

resources:
  Resources:
    TODOSDynamoDBTABLE:
     Type: AWS::DyanoDB::Table
     Properties:
      AttributesDefinitions:
       - AttributeName: partitionKey
         AttributeType: S
       - AttributeName: sortKey
         AttributeType: S
       - AttributeName: indexKey
         AttributeType: S
       - AttributeName: name
         AttributeType: S         
       - AttributeName: createdAt
         AttributeType: timestamp
       - AttributeName: dueDate
         AttributeType: S
       - AttributeName: done
         AllowedValues:
            - true
            - false
         Default: false 
       - AttributeName: attachmentUrl
         AttributeType: S      
      KeySchema:
       - AttributeName: partitionKey
         KeyType: HASH
       - AttributeName: sortKey
         KeyType: RANGE  
      LocalSecondaryIndexes:
        - IndexName: ${self:provider.environment.TODO_ID_INDEX}
          KeySchema:
          - AttributeName: partitionKey
            KeyType: HASH
          - AttributeName: sortKey
            KeyType: RANGE  
          Projection:
            ProjectionType: ALL                  
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:provider.environment.TODO_TABLE}
        